
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-09
owner: ucsb-cs156-s25
repo_name: team02-s25-09
pull_requests: [{"author":{"id":"U_kgDOCMMDPQ","is_bot":false,"login":"jasozh5","name":""},"headRefName":"jason-MenuItemReview-backend2","number":75,"title":"jz - copied backend CRUD from team01 into team02","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/75"},{"author":{"id":"U_kgDOB3DxTg","is_bot":false,"login":"moiez12","name":""},"headRefName":"MB-ArticlesForm","number":74,"title":"MB-ArticlesForm Created ArticlesForm,ArticlesForm.stories and ArticlesForm.test","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/74"},{"author":{"id":"U_kgDOBz88Iw","is_bot":false,"login":"RubenAlvarezGJ","name":"iamruben"},"headRefName":"ra-UCSBDiningCommonsMenuItem-components-and-tests","number":71,"title":"ra - stories and tests for UCSBDiningCommonsMenuItemForm","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/71"}]
