
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-09
owner: ucsb-cs156-s25
repo_name: team02-s25-09
pull_requests: [{"author":{"id":"U_kgDOCM71xg","is_bot":false,"login":"JiaaoZheng","name":""},"headRefName":"Fred-UCSBOrganization-Dokku","number":64,"title":"( ' - ' )Fred ucsb organization dokku deployment + added stuff from team01","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/64"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-rr2","number":63,"title":"AK - Add Javascript Fixtures for RR Table ","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/63"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-rr1","number":61,"title":"AK - copy backend CRUD operations from team01-dev for the commits table","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/61"}]
