
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-09
owner: ucsb-cs156-s25
repo_name: team02-s25-09
pull_requests: [{"author":{"id":"U_kgDOB3D27Q","is_bot":false,"login":"Jsanchez021","name":""},"headRefName":"js-helprequest-table","number":113,"title":"js - add help request table, tests, and stories","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/113"},{"author":{"id":"U_kgDOCMMDPQ","is_bot":false,"login":"jasozh5","name":""},"headRefName":"jz-create-menuitemreview-page","number":111,"title":"Jz create menuitemreview page","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/111"},{"author":{"id":"U_kgDOCMMDPQ","is_bot":false,"login":"jasozh5","name":""},"headRefName":"jz-menuitemreview-placeholderpages","number":104,"title":"Jz menuitemreview placeholderpages","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/104"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-rr5-placeholder","number":94,"title":"AK - Adding placeholder pages for Index, Edit, and Create for Commits","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/94"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-rr4","number":93,"title":"AK - Commit Table","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/93"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-rr3","number":91,"title":"Ak - Add Form for RecommendationRequest","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/91"}]
