
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-09
owner: ucsb-cs156-s25
repo_name: team02-s25-09
pull_requests: [{"author":{"id":"U_kgDOCMMDPQ","is_bot":false,"login":"jasozh5","name":""},"headRefName":"jz-editpage3","number":140,"title":"menu item reviews edit and index pages","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/140"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-e2e","number":133,"title":"AK - E2E Testing Finished","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/133"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-integration","number":124,"title":"AK - RecommendationRequest IT tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/124"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-rr8-edit","number":118,"title":"AK - Edit Recommendation Request Page (CHECKMARK MISSING CUZ OF THE PAYMENT THINGY IGNORE)","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/118"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-rr7-index","number":117,"title":"AK - Index RecommendationRequest Page (CHECKMARK MISSING CUZ OF THE PAYMENT THINGY IGNORE)","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/117"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-rr6-create","number":116,"title":"AK - Create RecommendationRequest Page (CHECKMARK MISSING CUZ OF THE PAYMENT THINGY IGNORE)","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/116"}]
