
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-09
owner: ucsb-cs156-s25
repo_name: team02-s25-09
pull_requests: [{"author":{"id":"U_kgDOB3DxTg","is_bot":false,"login":"moiez12","name":""},"headRefName":"MB-articlesFixtures","number":67,"title":"MB-articlesFixture Frontend","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/67"},{"author":{"id":"U_kgDOBz88Iw","is_bot":false,"login":"RubenAlvarezGJ","name":"iamruben"},"headRefName":"ra-UCSBDiningCommonsMenuItem-backend","number":66,"title":"ra-UCSBDiningCommonsMenuItem backend code","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/66"},{"author":{"id":"U_kgDOB3DxTg","is_bot":false,"login":"moiez12","name":""},"headRefName":"MB-FirstStepArticles","number":65,"title":"MB - CRUD operations for Articles","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/65"},{"author":{"id":"U_kgDOCM71xg","is_bot":false,"login":"JiaaoZheng","name":""},"headRefName":"Fred-UCSBOrganization-Dokku","number":64,"title":"( ' - ' )Fred ucsb organization dokku deployment + added stuff from team01","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/64"}]
