
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-09
owner: ucsb-cs156-s25
repo_name: team02-s25-09
pull_requests: [{"author":{"id":"MDQ6VXNlcjQzMTU1MjY4","is_bot":false,"login":"smmzhu","name":"Samuel Zhu"},"headRefName":"sam-test","number":147,"title":"f","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/147"},{"author":{"id":"U_kgDOCMMDPQ","is_bot":false,"login":"jasozh5","name":""},"headRefName":"jz-menuitemreview-integrationtest","number":144,"title":"Jz menuitemreview integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/144"}]
