
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-09
owner: ucsb-cs156-s25
repo_name: team02-s25-09
pull_requests: [{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-rr3","number":91,"title":"Ak - Add Form for RecommendationRequest","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/91"},{"author":{"id":"U_kgDOCM71xg","is_bot":false,"login":"JiaaoZheng","name":""},"headRefName":"Fred-UCSBOrganization-Pages","number":90,"title":"Fred ucsb organization pages Done","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/90"},{"author":{"id":"U_kgDOCMMDPQ","is_bot":false,"login":"jasozh5","name":""},"headRefName":"jz-commit-fixtures","number":89,"title":"jz-create fixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/89"},{"author":{"id":"U_kgDOB3DxTg","is_bot":false,"login":"moiez12","name":""},"headRefName":"MB-EditPage","number":87,"title":"Mb - Edit Articles Page","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/87"},{"author":{"id":"U_kgDOB3DxTg","is_bot":false,"login":"moiez12","name":""},"headRefName":"MB-ArticlesIndex","number":86,"title":"Mb - ArticlesIndex","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/86"},{"author":{"id":"U_kgDOCM71xg","is_bot":false,"login":"JiaaoZheng","name":""},"headRefName":"Fred-UCSBOrganization-CreatingForms","number":85,"title":"Fred ucsb organization creating forms","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/85"},{"author":{"id":"U_kgDOBz88Iw","is_bot":false,"login":"RubenAlvarezGJ","name":"iamruben"},"headRefName":"ra-ucsbdiningcommonsmenuitem-edit-page","number":83,"title":"ra - ucsbdiningcommonsmenuitem edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/83"},{"author":{"id":"U_kgDOBz88Iw","is_bot":false,"login":"RubenAlvarezGJ","name":"iamruben"},"headRefName":"ra-ucsbdiningcommonsmenuitem-index-page","number":82,"title":"ra - ucsbdiningcommonsmenuitem index page","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/82"},{"author":{"id":"U_kgDOBz88Iw","is_bot":false,"login":"RubenAlvarezGJ","name":"iamruben"},"headRefName":"ra-create-ucsbdiningcommonsmenuitem-page","number":81,"title":"ra - create ucsbdiningcommonsmenuitem page","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/81"},{"author":{"id":"U_kgDOBz88Iw","is_bot":false,"login":"RubenAlvarezGJ","name":"iamruben"},"headRefName":"ra-UCSBDiningCommonsMenuItem-placeholder-pages","number":79,"title":"ra - added placeholder pages for Index, Edit, Create for UCSBDiningCo…","url":"https://github.com/ucsb-cs156-s25/team02-s25-09/pull/79"}]
